application: arx
version: dev
runtime: python
api_version: 1



error_handlers:

- error_code: over_quota
  file: errors/quota.html

- error_code: dos_api_denial
  file: errors/dos.html

- error_code: timeout
  file: errors/timeout.html

#- file: errors/default.html



handlers:

#static files

- url: /v7setup
  static_dir: static/v7setup

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt



#public controllers

- url: /
  script: controllers/frontpage.py

- url: /bulka
  script: controllers/bulka.py



#protected controllers

- url: /catalog
  script: controllers/catalog.py
  login: required

- url: /person
  script: controllers/person.py
  login: required



#ARX-Raamat 7

- url: /v7(.*)
  script: controllers/v7.py

- url: /help(.*)
  script: controllers/v7.py

- url: /registreerimine.php
  script: controllers/v7.py

- url: /versioon.php
  script: controllers/v7.py

- url: /vearaport.php
  script: controllers/v7.py