application: arx-raamat
version: dev
runtime: python
api_version: 1



error_handlers:

- error_code: over_quota
  file: errors/quota.html

- error_code: dos_api_denial
  file: errors/dos.html

- error_code: timeout
  file: errors/timeout.html

#- file: errors/default.html



handlers:

#BO Framework
- url: /_ah/login_required
  script: bo/controllers/login.py

- url: /login(.*)
  script: bo/controllers/login.py

- url: /user(.*)
  script: bo/controllers/user.py
  login: required



#static files
- url: /v7setup
  static_dir: static/v7setup

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript



#controllers
- url: /beta
  script: controllers/frontpage.py
  login: required

- url: /catalog
  script: controllers/catalog.py
  login: required

- url: /person
  script: controllers/person.py
  login: required

- url: /v7(.*)
  script: controllers/v7.py

- url: /
  script: controllers/v7.py